version: 2
jobs:
    build:
        working_directory: ~/CircleCIProj
        docker:
          - image: microsoft/dotnet:sdk
        steps:
          - checkout
          - run: dotnet restore XUnitTestProj2
          - run: dotnet build XUnitTestProj2
          - run: dotnet test XUnitTestProj2

