version: 2
jobs:
    buildCore:
        working_directory: ~/dotnet
        docker:
        steps:
          - checkout
          - run: apt-get update 
          - run: apt-get install -y nuget mono-devel mono-xbuild
          - run: nuget update -self
          - run: xbuild 

workflows:
  version: 2
  build123:
    jobs:
      - buildCore
    