version: 2
jobs:
    build:
        working_directory: ~/CircleCIProj
        docker:
          - image: microsoft/dotnet:sdk
        steps:
          - checkout
          - run: dotnet restore
          - run: dotnet build
          - run: dotnet test

