version: 2
jobs:
    buildCore:
        working_directory: ~/dotnet
        windows:
        steps:
          - checkout
          - run: apt-get update && apt-get install -y mono-complete 5.8.0
          - run: xbuild 
          - run: dotnet test 

workflows:
  version: 2
  build123:
    jobs:
      - buildCore