version: 2
jobs:
    buildCore:
        working_directory: ~/EmptyWebApplication
        docker:
            - image: microsoft/dotnet:sdk
        steps:
          - checkout
          - run: apt-get update 
          - run: apt-get install -y nuget mono-complete
          - run: xbuild

workflows:
  version: 2
  build123:
    jobs:
      - buildCore
    
    


