version: 2
jobs:
    buildCore:
        working_directory: ~/benchmark-dotnet-mono-build-webapi-master
        docker:
            - image: microsoft/dotnet:sdk
        steps:
          - checkout
          - run: apt-get update 
          - run: apt-get install -y nuget mono-complete
          - run: nuget update -self
          - run:  cd benchmark-dotnet-mono-build-webapi-master && nuget restore
          - run: benchmark-dotnet-mono-build-webapi-master && xbuild

workflows:
  version: 2
  build123:
    jobs:
      - buildCore
    
    


