version: 2
jobs:
    buildCore:
        working_directory: ~/dotnet
        docker:
            - image: microsoft/dotnet:sdk
        steps:
          - checkout
          - run: apt-get update 
          - run: apt-get install -y nuget mono-complete=5.0.0
          - run: nuget update -self
          - run: nuget restore
          - run: xbuild

workflows:
  version: 2
  build123:
    jobs:
      - buildCore
    