version: 2
jobs:
    buildCore:
        working_directory: ~/CoreDotNet
        docker:
          - image: microsoft/dotnet:sdk
        steps:
          - checkout
          - run: apt-get update && apt-get install -y mono-complete 
          - run: dotnet restore 
          - run: xbuild 
          - run: dotnet test 

workflows:
  version: 2
  build123:
    jobs:
      - buildCore