version: 2
jobs:
    buildCore:
        working_directory: ~/CoreDotNet
        docker:
          - image: microsoft/dotnet:sdk
        steps:
          - checkout
          - run: dotnet restore 
          - run: dotnet build 
          - run: dotnet test 

workflows:
  version: 2
  build123:
    jobs:
      - buildCore